import { useEffect, useState } from 'react';
import { api } from '../core/api';

const blank = { title: '', department: '', description: '', status: 'draft', questions: 'How would you rate your visit?|rating|true' };
const toQuestions = (text) => text.split('\n').filter(Boolean).map((line) => {
  const [prompt, type = 'rating', required = 'false'] = line.split('|').map((part) => part.trim());
  return { prompt, type, required: required === 'true' };
});

export default function App() {
  const [user, setUser] = useState(JSON.parse(localStorage.getItem('teamInformaticsUser') || 'null'));
  const [surveys, setSurveys] = useState([]); const [form, setForm] = useState(blank); const [editing, setEditing] = useState(null); const [notice, setNotice] = useState('');
  const load = async () => { if (user) setSurveys(await api('/surveys')); };
  useEffect(() => { load().catch((e) => setNotice(e.message)); }, [user]);
  const signIn = async (event, register = false) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); try { const data = await api(`/auth/${register ? 'register' : 'login'}`, { method: 'POST', body: JSON.stringify(values) }); localStorage.setItem('teamInformaticsToken', data.token); localStorage.setItem('teamInformaticsUser', JSON.stringify(data.user)); setUser(data.user); } catch (e) { setNotice(e.message); } };
  const save = async (event) => { event.preventDefault(); try { const payload = { ...form, questions: toQuestions(form.questions) }; await api(editing ? `/surveys/${editing}` : '/surveys', { method: editing ? 'PATCH' : 'POST', body: JSON.stringify(payload) }); setNotice('Survey saved successfully.'); setForm(blank); setEditing(null); load(); } catch (e) { setNotice(e.message); } };
  if (!user) return <main className="auth"><h1>✚ Team Informatics</h1><p>Healthcare feedback, heard clearly.</p><section><form onSubmit={signIn}><h2>Sign in</h2><input name="email" type="email" placeholder="Email" required/><input name="password" type="password" placeholder="Password" required/><button>Sign in</button></form><form onSubmit={(e) => signIn(e, true)}><h2>Register staff</h2><input name="name" placeholder="Name" required/><input name="email" type="email" placeholder="Email" required/><input name="password" type="password" placeholder="Password (6+ characters)" minLength="6" required/><button>Create account</button></form></section>{notice && <p className="notice">{notice}</p>}</main>;
  return <main><header><div><h1>Team Informatics Surveys</h1><p>Welcome, {user.name}</p></div><button onClick={() => { localStorage.clear(); setUser(null); }}>Log out</button></header><p className="notice">{notice}</p><section className="layout"><form onSubmit={save}><h2>{editing ? 'Edit survey' : 'Create survey'}</h2><input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Survey title" required/><input value={form.department} onChange={(e) => setForm({ ...form, department: e.target.value })} placeholder="Department" required/><textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Description"/><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option value="draft">Draft</option><option value="published">Published</option><option value="closed">Closed</option></select><textarea value={form.questions} onChange={(e) => setForm({ ...form, questions: e.target.value })} required/><small>One per line: question | rating, text, or yes-no | true/false</small><button>Save survey</button>{editing && <button type="button" onClick={() => { setEditing(null); setForm(blank); }}>Cancel</button>}</form><div><h2>Your surveys</h2>{surveys.map((survey) => <article key={survey._id}><span>{survey.status}</span><h3>{survey.title}</h3><p>{survey.department}</p><p>{survey.description}</p><button onClick={() => { setEditing(survey._id); setForm({ ...survey, questions: survey.questions.map((q) => `${q.prompt}|${q.type}|${q.required}`).join('\n') }); }}>Edit</button><button onClick={async () => { if (confirm('Delete this survey?')) { await api(`/surveys/${survey._id}`, { method: 'DELETE' }); load(); } }}>Delete</button></article>)}</div></section></main>;
}
